project:
  type: book
  output-dir: docs

book:
  title: "The AQuA Book"
  author: "Government Analysis Function"
  date: "10/08/2024"
  chapters:
    - index.qmd
    - foreword.qmd
    - intro.qmd
    - definitions_and_key_concepts.qmd
    - proportionality.qmd
    - quality_assurance_culture.qmd
    - analytical_lifecycle.qmd
    - engagement_and_scoping.qmd
    - design.qmd
    - analysis.qmd
    - delivery_and_communication.qmd
    - additional_resources.qmd
    - improving_the_book.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly



