::: {.callout-important}
This version of the AQuA book is a preliminary ALPHA draft.  It is still in development, and we are still working to ensure that it meets user needs. 

The draft currently has no official status. It is a work in progress and is subject to further revision and reconfiguration (possibly substantial change) before it is finalised. 
:::

# Delivery communication and sign-off

## Introduction and overview

The successful delivery of analysis to its Commissioner marks its transition from being a product under development to one that is fit and ready to be used to inform decision making in your organisation and possibly inform the public. 

This chapter provides information on the processes around assurance of communication of analysis and delivery of analytical output.

## Responsibilities by role

### Analyst

- The Analyst shall follow organisational governance procedures for delivery and sign-off, including, where appropriate, updating the [business-critical model register](#Business-critical model register), and making the analysis [publicly available](#Publishing analysis).
- The Analyst should ensure that communication meets audience requirements, including accessibility.
- The Analyst may be required to communicate the assurance state to the Approver, if not done directly by the Assurer.
- The Analyst should be prepared to respond to challenge from the Approver. For example, this challenge could take place during project or programme board 

### Assurer

The Assurer shall communicate the assurance state to the Approver. This includes confirmation that the work has been appropriately scoped, executed, validated, verified, documented, and provides adequate handling of uncertainty. This communication may go via the Analyst.

### Commissioner

The Commissioner shall use the analysis as specified at the start of the analytical cycle, applying any limitations to its use as described by the Analyst.

### Approver
The Approver shall review the assurance evidence that has been provided by the Assurer. The Approver should provide sufficient challenge to the analysts to gain assurance that the analysis is fit for purpose. 

When they are satisfied with the validity and robustness of the analysis, the Approver should  provide the analyst with evidence that the analysis outputs have been properly reviewed and formally approved.



## Assurance activities in the delivery, communication and sign-off stage

## Delivering the analysis

When delivering a piece of analysis, the Analyst and/or Assurer should communicate its assurance state to the Approver and provide evidence that the analysis and associated outputs have undergone proportionate quality assurance and there is adequate evidence to demonstrate that the analysis is ready for delivery, for example:
    
* It uses suitable data and assumptions as agreed with the commissioner;    
* It meets the purpose of its commission;    
* It has been carried out correctly and to its agreed specification;   
* It has a risk assessment and statement against the programme risk register;
* If meets analytical standards
* It adheres to any professional codes of practice (e.g. [The Code of Practice for Statistics)(https://code.statisticsauthority.gov.uk/)
* Where appropriate the analysis is accompanied by a completed [assurance statement](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fassets.publishing.service.gov.uk%2Fmedia%2F65c5021f9c5b7f0012951b83%2F20231101-analysis-evidence-quality-assurance-report-gov-uk-E02.docx&wdOrigin=BROWSELINK).   

Though not strictly assurance, the analyst should also consider areas such as security ratings, retention policies, intellectual property, ethics and related concerns.


The Approver should scrutinise the evidence delivered and approve it if the analysis meets the agreed criteria. The Approver should then feedback the outcome of any approval activities to the analyst so that the analysis can be updated if required. The Approver should also provide the analyst with evidence that the analysis outputs have been properly reviewed and formally approved. For example, through the notes of a project / programme board where the decision to approve the analysis was made or similar. 

The exact nature of any scrutiny made by the Approver should be proportionate to the impact of the analysis, the governance process of their programme / organisation and follow the principles of proportionality described in [Chapter 3](#proportionality.qmd) of this document. 

To ensure that the analysis is used as intended, the Commissioner should use the analysis as specified at the start of the analytical cycle, applying any limitations to its use as described by the Analyst. 

## Communicating the analysis

The effective and transparent communication is essential to enable analysis to be adopted and trusted by the Commissioner and onward users. Depending on its final use and likelihood of publication, any analysis may be communicated to a wide audience including:

* Commissioners and users of the analysis;    
* External scrutiny including the [Public Accounts Committee](https://committees.parliament.uk/committee/127/public-accounts-committee/), the [National Audit Office](https://www.nao.org.uk/), internal and external audit;    
* The public, through publications and [Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/contents) requests;    
* Academic experts, possibly through a departmental [Areas of Research Interest](https://www.gov.uk/government/publications/dwp-areas-of-research-interest-2023/dwp-areas-of-research-interest-2023) document. 
* Governmental partners - both national and international

The form of communication should be tailored to the audience. The communication should be quality assured in a proportionate manner to ensure an accurate reflection of the analytical results.

The Analysis Function's [Making Analytical Publications Accessible Toolkit](https://analysisfunction.civilservice.gov.uk/policy-store/making-analytical-publications-accessible/) gives guidance to help ensure that any that websites, tools, and technologies produced from analysis are designed and developed so that people with disabilities can use them. More specifically, people can: perceive, understand, navigate, and interact with the web.

If publishing the outcome of any analysis is required, the analyst should follow departmental and statutory guidance. The analyst must comply with the code of practice when they publish official statistics.  Some examples are given below:

* If you are publishing statistics you will need to follow your organisation's guidance and the [regulatory guidance for publishing official statistics and national statistics](https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-publishing-official-statistics-and-national-statistics/) ;    
* If you are publishing research, you shall follow your organisations guidance and the [Government Social Research Publication protocol](https://www.gov.uk/government/publications/government-social-research-publication-protocols);    
* If you are publishing an evaluation, refer to any recommendations from the [Evaluation Task Force](https://www.gov.uk/government/organisations/evaluation-task-force);    

### Sign-off
The exact nature of the approval process may vary depending on:

* The impact of the analysis;    
* The approval process of the organisation, and    
* The nature of the programme, project or board approving the analysis. 


## Documentation


The Approver should scrutinise the evidence delivered and approve it if the analysis meets the agreed criteria. The Approver should then feedback the outcome of any approval activities to the analyst so that the analysis can be updated if required. The Approver should also provide the analyst with evidence that the analysis outputs have been properly reviewed and formally approved. For example, through the notes of a project / programme board where the decision to approve the analysis was made or similar. 

The exact nature of any scrutiny made by the Approver should be proportionate to the impact of the analysis, the governance process of their programme / organisation and follow the principles of proportionality described in [Chapter 3](#proportionality.qmd) of this document. 

To ensure that the analysis is used as intended, the Commissioner should use the analysis as specified at the start of the analytical cycle, applying any limitations to its use as described by the Analyst. 

## Communicating the analysis

Effective and transparent communication is essential to enable analysis to be adopted and trusted by the Commissioner and onward users. Depending on its final use and likelihood of publication, any analysis may be communicated to a wide audience including:

* Commissioners and users of the analysis;    
* External scrutiny including the [Public Accounts Committee](https://committees.parliament.uk/committee/127/public-accounts-committee/), the [National Audit Office](https://www.nao.org.uk/), internal and external audit;    
* The public, through publications and [Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/contents) requests;    
* Academic experts, possibly through a departmental [Areas of Research Interest](https://www.gov.uk/government/publications/dwp-areas-of-research-interest-2023/dwp-areas-of-research-interest-2023) document. 
* Governmental partners - both national and international

The form of communication should be tailored to the audience. The communication should be quality assured in a proportionate manner to ensure an accurate reflection of the analytical results.

The Analysis Function's [Making Analytical Publications Accessible Toolkit](https://analysisfunction.civilservice.gov.uk/policy-store/making-analytical-publications-accessible/) gives guidance to help ensure that any that websites, tools, and technologies produced from analysis are designed and developed so that people with disabilities can use them. More specifically, people can: perceive, understand, navigate, and interact with the web.

If publishing the outcome of any analysis is required, the analyst should follow departmental and statutory guidance. The analyst must comply with the code of practice when they publish official statistics.  Some examples are given below:

* If you are publishing statistics you will need to follow your organisation's guidance and the [regulatory guidance for publishing official statistics and national statistics](https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-publishing-official-statistics-and-national-statistics/) ;    
* If you are publishing research, you shall follow your organisations guidance and the [Government Social Research Publication protocol](https://www.gov.uk/government/publications/government-social-research-publication-protocols);    
* If you are publishing an evaluation, refer to any recommendations from the [Evaluation Task Force](https://www.gov.uk/government/organisations/evaluation-task-force);    

### Sign-off
The exact nature of the approval process may vary depending on:

* The impact of the analysis;    
* The approval process of the organisation, and    
* The nature of the programme, project or board approving the analysis. 


## Documentation


The Approver should scrutinise the evidence delivered and approve the work if the analysis meets the required standard, which considers the [proportionality](proportionality.html) of the work. The Approver should then feedback the outcome of any approval activities to the analyst so that the analysis can be updated if required.  

The exact nature of any scrutiny made by the Approver should be proportionate to the impact of the analysis, the governance process of their programme/ organisation, and follow the principles of proportionality described in [Chapter 3](proportionality.html) of this document. 

To ensure that the analysis is used as intended, the Commissioner should use the analysis as specified at the start of the analytical cycle, applying any limitations to its use as described by the Analyst. 

### Communication

The effective and transparent communication is essential to enable analysis to be adopted and trusted by the Commissioner and onward users. Depending on its final use and likelihood of publication, any analysis may be communicated to a wide audience including:

* Commissioners and users of the analysis;    
* External scrutiny including the [Public Accounts Committee](https://committees.parliament.uk/committee/127/public-accounts-committee/), the [National Audit Office](https://www.nao.org.uk/), internal and external audit;    
* The public, through publications and [Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/contents) requests;    
* Academic experts, possibly through a departmental [Areas of Research Interest](https://www.gov.uk/government/publications/dwp-areas-of-research-interest-2023/dwp-areas-of-research-interest-2023) document. 
* Governmental partners - both national and international

The form of communication should be tailored to the audience. The communication should be quality assured in a proportionate manner to ensure an accurate reflection of the analytical results.

The Analysis Function's [Making Analytical Publications Accessible Toolkit](https://analysisfunction.civilservice.gov.uk/policy-store/making-analytical-publications-accessible/) gives guidance to help ensure that any that websites, tools, and technologies produced from analysis are designed and developed so that people with disabilities can use them. More specifically, people can: perceive, understand, navigate, and interact with the web.

If publishing the outcome of any analysis is required, the Analyst should follow departmental and statutory guidance.Some examples are given below:

* If you are publishing statistics you will need to follow your organisation's guidance and the [regulatory guidance for publishing official statistics and national statistics](https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-publishing-official-statistics-and-national-statistics/) ;    
* If you are publishing research, you shall follow your organisations guidance and the [Government Social Research Publication protocol](https://www.gov.uk/government/publications/government-social-research-publication-protocols);    
* If you are publishing an evaluation, refer to any recommendations from the [Evaluation Task Force](https://www.gov.uk/government/organisations/evaluation-task-force);    

### Sign-off
The exact nature of the approval process may vary depending on:

* The impact of the analysis;    
* The approval process of the organisation, and    
* The nature of the programme, project or board approving the analysis. 

The formality of the sign-off process should be governed by organisational procedures, and be proportionate to the analysis.

The Approver should provide the Analyst with evidence that the analysis outputs have been properly reviewed and formally approved. For example, through the notes of a project / programme board where the decision to approve the analysis was made or similar.

## Documention in the delivery, communication and sign-off stage

When the Analyst and Assurer are satisfied that the analysis is ready to hand over to the Commissioner, they should ensure that any associated documentation supporting the analysis is ready and has also undergone quality assurance.  Supporting documentation might include:

* [Specification](definitions_and_key_concepts.html#specification_documentation) and [design documentation](definitions_and_key_concepts.html#design_documentation)
* Logs of [data](definitions_and_key_concepts.html#data-log), [assumptions](definitions_and_key_concepts.html#assumptions-log) and [decisions](definitions_and_key_concepts.html#decisions-log) including their source, ownership, reliability and any sensitivity analysis carried out; 
* [User and technical documentation](definitions_and_key_concepts.html#user-technical-documentation)
* Advice on uncertainty and its impact on the outputs of the analysis;    
* A description of the limits of the analysis and what it can and cannot be used for;    
* Any materials for presenting the analysis to the Commissioner, for example slide decks or reports;    
* A record of the analysis including methods used, dependencies, process maps, change and version control logs and error reporting;    
* The code-base, when it has been agreed to [publish the analysis openly](#open-publishing-of-analysis)
* The test plan and results of the tests made against that plan;    
* A statement of assurance;    
* Any ethical concerns that have been addressed, especially for the application of Artificial Intelligence and machine learning algorithms;    
* Where applicable ensuring that the analysis meets the [accessibility requirements for public bodies](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps) and / or 
* Where applicable the code of practice for publications has been followed.    


## Treatment of uncertainty in the delivery, communication and sign-off stage

Government has produced a range of guidance to support analysts in presenting and communicating uncertainty in analysis. This includes:

* The Office for Statistical Regulation’s [Approaches to presenting uncertainty in the statistical system](https://osr.statisticsauthority.gov.uk/publication/approaches-to-presenting-uncertainty-in-the-statistical-system/);    * The [Uncertainty Toolkit for Analysts](https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/chapter_6.html);    
* The Government Analysis Function guidance note [Communicating quality, uncertainty and change](https://analysisfunction.civilservice.gov.uk/policy-store/communicating-quality-uncertainty-and-change/);    

Each provides valuable advice on how to estimate and present uncertainty when describing the limitations of use of a piece of analysis.

## AI/ML and the delivery, communication and sign-off stage

The Approver is responsible for signing-off that all risks and ethical considerations around the use of black-box models have been addressed. The aspects to be considered are detailed in the [Introduction to AI assurance](https://www.gov.uk/government/publications/introduction-to-ai-assurance).


## Multi-use models and the delivery, communication and sign-off stage

There is a greater risk that multi-use models may be used for purposes outside the intended scope. This places a greater onus on the Analyst to clearly communicate to all users the limitations and intended use. The Analyst may consider testing communication with different user groups to ensure that the analytical outputs are used as intended.

## Analytical transparency   

Enabling the public to understand and scrutinise analysis promotes public confidence in decisions. This includes enabling the public to have information on models used for [business-critical decisions](#Business-critical model register) and [making analysis open](#Open-publishing-of-analysis)
### Business-critical model register

### Open publishing ofanalysis
